name: zero_setup_flutter
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^17.0.0

  # State Management
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1

  # Database
  isar: ^3.1.0+1

  # Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

  # Networking
  dio: ^5.9.0
  retrofit: ^4.9.1
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^7.0.0

  # UI Components
  flex_color_scheme: ^8.4.0
  responsive_framework: ^1.5.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2
  gap: ^3.0.1
  cupertino_icons: ^1.0.8

  # Utilities
  fpdart: ^1.2.0
  permission_handler: ^12.0.1
  envied: ^1.3.2

  # Logging
  talker: ^5.1.5
  talker_dio_logger: ^5.1.5
  talker_flutter: ^5.1.5
  talker_riverpod_logger: ^5.1.5
  talker_logger: ^5.1.5

  # Code Generation Annotations
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  mocktail: ^1.0.4

  # Linting
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3
  flutter_lints: ^6.0.0

  # Code Generation
  retrofit_generator: ^10.2.0
  flutter_gen_runner: ^5.12.0
  freezed: ^3.2.3
  json_serializable: ^6.11.3
  envied_generator: ^1.3.2
  build_runner: ^2.10.4

flutter_gen:
  output: lib/core/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
